### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by johbom** [wubbl0rz/FiatChamp#4]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
The build failed. Fix the build errors and run again.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
/root/.dotnet/sdk/7.0.100-rc.1.22431.12/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1187: Package Cocona 2.0.3 has a resource with the locale 'ja-jp'. This locale has been normalized to the standard format 'ja-JP' to prevent casing issues in the build. Consider notifying the package author about this casing issue. [/FiatClient/FiatChamp.csproj]
/root/.dotnet/sdk/7.0.100-rc.1.22431.12/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1187: Package Cocona 2.0.3 has a resource with the locale 'ko-kr'. This locale has been normalized to the standard format 'ko-KR' to prevent casing issues in the build. Consider notifying the package author about this casing issue. [/FiatClient/FiatChamp.csproj]
/root/.dotnet/sdk/7.0.100-rc.1.22431.12/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1187: Package Cocona.Core 2.0.3 has a resource with the locale 'ja-jp'. This locale has been normalized to the standard format 'ja-JP' to prevent casing issues in the build. Consider notifying the package author about this casing issue. [/FiatClient/FiatChamp.csproj]
/root/.dotnet/sdk/7.0.100-rc.1.22431.12/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1187: Package Cocona.Core 2.0.3 has a resource with the locale 'ko-kr'. This locale has been normalized to the standard format 'ko-KR' to prevent casing issues in the build. Consider notifying the package author about this casing issue. [/FiatClient/FiatChamp.csproj]

**Comment by wubbl0rz** [comment]
are you running on a raspberry ?  i never testet it on one

**Comment by wubbl0rz** [comment]
i just reinstalled it on my home assistant x86 box and it builds and starts without issues. whats strange is that it says it failed but afterwards the normal build output is show :thinking:

**Comment by wubbl0rz** [comment]
today i tested it on a new pi 4 with 64bit home assistant os and it works without any errors

**Comment by johbom** [comment]
For me it's still crashing Hassio. 

Log:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
/root/.dotnet/sdk/7.0.100-rc.1.22431.12/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1187: Package Cocona 2.0.3 has a resource with the locale 'ja-jp'. This locale has been normalized to the standard format 'ja-JP' to prevent casing issues in the build. Consider notifying the package author about this casing issue. [/FiatClient/FiatChamp.csproj]
/root/.dotnet/sdk/7.0.100-rc.1.22431.12/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1187: Package Cocona 2.0.3 has a resource with the locale 'ko-kr'. This locale has been normalized to the standard format 'ko-KR' to prevent casing issues in the build. Consider notifying the package author about this casing issue. [/FiatClient/FiatChamp.csproj]
/root/.dotnet/sdk/7.0.100-rc.1.22431.12/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1187: Package Cocona.Core 2.0.3 has a resource with the locale 'ja-jp'. This locale has been normalized to the standard format 'ja-JP' to prevent casing issues in the build. Consider notifying the package author about this casing issue. [/FiatClient/FiatChamp.csproj]
/root/.dotnet/sdk/7.0.100-rc.1.22431.12/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1187: Package Cocona.Core 2.0.3 has a resource with the locale 'ko-kr'. This locale has been normalized to the standard format 'ko-KR' to prevent casing issues in the build. Consider notifying the package author about this casing issue. [/FiatClient/FiatChamp.csproj]
The build failed. Fix the build errors and run again.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by kduchrow** [comment]
I also have to confirm that the plugin leads to a crash of homeassistant. At some point, homeassistant crashes so that I can't reach it anymore. That's why I can't send any logs. I also have Homeassistant running on a Rasberry Pi4. I have now turned off almost everything and was able to narrow it down to FiatChamp. The AddOn starts normally, but after some time (about 2 hrs) Homeassistant is no longer reachable. 
I have the feeling that the addon needs a lot of resources (RAM in particular). Can it be that maybe something is filling up there with time?
Could this also have something to do with this problem here?
I have now disabled the AddOn and everything is running smoothly again for a few days. So it seems to be due to the AddOn

**Comment by wubbl0rz** [comment]
you guys are right. looks like the aws library that im using for login (the official one btw 😅) wants to take 600MB amounts of ram on first use. what the hell 😆 i never noticed this because my home assistant box has much more memory than a small raspberry pi. i will have a look tomorrow how this can be removed.

**Comment by wubbl0rz** [comment]
found the issue. ram usage is down from 700MB to 114MB :sweat_smile: upgrades and installation should be much faster too  because its using an prebuilt image. 

update 2.0.5 will be available today or tomorrow.

**Comment by wubbl0rz** [comment]
@kduchrow  @johbom  please try again with version 2.0.6. should be available now. problem was high memory usage because of local dotnet build. addon runs now from a prebuilt image. should only use ~115MB of ram. tested in my pi4 and amd64 desktop.

**Comment by kduchrow** [comment]
As soon as I get the update in home assistant, I'm going to install the whole thing, test it and give you feedback.
Thank you for you quick fix !

**Comment by kduchrow** [comment]
Hi, I did the Update with the same issue as in the new [https://github.com/wubbl0rz/FiatChamp/issues/5](Issue).
But after reinstalling and reconfiguring the Addon works fine for me and consumes way fewer resources. Nice !

The only annoying thing I experience (But it has nothing to do with this AddOn) is, that every time the AddOn refreshes the Battery Status I get a notification on my Smartphone. The Notification tells me that the battery status was updated. Does anyone know how to suppress this? - So I have to deactivate the Reload of the Battery and Location. Maybe a "snooze time" of refresh could be a solution for that.

**Comment by wubbl0rz** [comment]
nice to hear that its working now 😀 

i would recommend not to use the reload and location update in the addon at all until you really have to. i had some special case in mind why someone would need this but i can't remember right now 😅 anyway its better to use a home assistant automation for this.

for example you can make a automation that updates the battery status only when your wallbox charger is active. since version 2.0.0 the addon has command support for a few things and integrated into home assistant. there is a button for "DeepRefresh" (which basically means battery status update in fiat language) and "UpdateLocation". you can see this and all sensors in the mqtt integration when clicking on the CAR entry. both can be used in a home assistant automation.

mine looking like this. the first one updates the battery every 15min when the charger is active and the second one sends me one time a message when charging is finished. both require a charger thats somehow integrated with home asisstant. hope this helps.

![image](https://user-images.githubusercontent.com/30373916/194615315-6a2cc793-bf10-4a0c-8a44-dba199d808f0.png)
![image](https://user-images.githubusercontent.com/30373916/194616421-e0ea0dc3-1946-4d42-bf55-e0ad4fc43ed4.png)

**Comment by loetman** [comment]
hi, i have an external MQTT Broker. Its working fine, all Sensor Data reading works. But how i can publish commands like "DeepRefresh"?
I tried a many options, but nothing works.
Here a sample of a Message: "publish homeassistant/button/ZFAxxxxxxxxxxxxx_DeepRefresh/set  1"
thanks for helping me.
