### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by theexit** [wubbl0rz/FiatChamp#5]
Update to version 2.0.6 failed with error:

Failed to to call /store/addons/d6ed25d9_fiat_champ/update - COPY failed: file not found in build context or excluded by .dockerignore: stat FiatClient/build/amd64/: file does not exist

**Comment by kduchrow** [comment]
yes, I got the same error.
My solution was, to uninstall the AddOn and reinstall it. But this needs to reconfigure the AddOn. 
So maybe have a look at the configuration before uninstalling

**Comment by theexit** [comment]
A reinstall worked for me too.

**Comment by wubbl0rz** [comment]
thx for reporting. didn't had the issue myself. i think thats because now its using an prebuilt docker image which is downloaded from github container registry (and now the addon using much less RAM than before). the old version was locally built for docker on the home assistant host. so maybe docker got confused and mixed local build with the new image idk 🥴

just updated the readme file with a notice for update to 2.0.6. issue should not occur again because all new release will use prebuilt images.
