### ISSUE TITLE
Km to Miles

### ISSUE THREAD

**Issue by bigstevehardy** [wubbl0rz/FiatChamp#7]
Not really an issue, (love the add on!) but would be nice to be able to toggle km or miles ?

**Comment by wubbl0rz** [comment]
thats a good idea. currently fiat only has km values as far as i know. but maybe i can do some post processing and/or try if its possible to internally switch the region to US.

**Comment by kduchrow** [comment]
Would it be possible to add the attribute "unit_of_measurement" to the HaSensor class? 
This could lead to the correct interpretation of Homeassistant and a better representation of the values.
Maybe this could also fix this problem as well?

**Comment by wubbl0rz** [comment]
please try again with 2.0.13 from today. during testing my home assistant bugged and did not accept new values via mqtt. i had to restart. so if new values do not show up try restarting first.

its not perfect because i do not know each value fiat has in their api. so i check if there are values with "km" as unit and convert them to miles. _unit sensors remains on "km" because thats what the api responds with but the actual value is converted to miles and gets the mi "unit_of_measurement" in home assistant.

# CHANGELOG

## 2.0.13 - 2022-10-16
- km to miles conversion
- distance sensors export unit of measurement to home assistant (km or mi)
- more fitting icons for some sensors
- obfuscate mail account in log
- fix debug logging

![image](https://user-images.githubusercontent.com/30373916/196038511-4d6eccd3-f5ab-49b2-8626-62af30e9fda1.png)

![image](https://user-images.githubusercontent.com/30373916/196038473-6d3fe8a4-4bff-405a-949c-61e7e55a7fd4.png)

**Comment by bigstevehardy** [comment]
Absolutely smashed it my Friend ! Working a treat and now in miles !!! Only thing not working is location but to be fair but a huge issue really !!

**Comment by wubbl0rz** [comment]
location should work. have a look at the attributes. it should show your location and can be used on the map card in the frontend. 

it just always says unknown on the main status :thinking: 

![image](https://user-images.githubusercontent.com/30373916/196045834-0d57657a-3ef0-4361-9340-7946778158e7.png)

**Comment by bigstevehardy** [comment]
Worked a treat, does the 15 min update frequency affect the fiat battery ?

**Comment by wubbl0rz** [comment]
you mean with location refresh enabled in the settings ? im not really sure because i dont force refresh location regularly. but it i think it should not be that much. or you could leave the refresh interval at 15 and dont enable location refresh. then setup an home assistant automation that call location refresh less often. maybe once per hour. 

![image](https://user-images.githubusercontent.com/30373916/196055514-860f3b44-178b-4f90-afa6-4c542feb46be.png)
